# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_static
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

# Configurations
# #############################################

RESCOMP = windres
DEFINES +=
INCLUDES += -Isrc/kernel
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug_static)
TARGETDIR = bin/Static/Debug
TARGET = $(TARGETDIR)/ckd
OBJDIR = obj/Static/Debug/ckd
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O0 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O0 -g -std=c++14
LIBS += bin/Static/Debug/libck.a -lcrypto -lsfml-network -lsfml-system -lleveldb -ljsoncpp -ljsonrpccpp-server -ljsonrpccpp-client -ljsonrpccpp-common -lmicrohttpd -lcschnorr -lpthread -llua5.3 -lcurl -ldl -lgcov
LDDEPS += bin/Static/Debug/libck.a
ALL_LDFLAGS += $(LDFLAGS) -rdynamic
endif

ifeq ($(config),debug_shared)
TARGETDIR = bin/Shared/Debug
TARGET = $(TARGETDIR)/ckd
OBJDIR = obj/Shared/Debug/ckd
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O0 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O0 -g -std=c++14
LIBS += bin/Shared/Debug/libck.so -lcrypto -lsfml-network -lsfml-system -lleveldb -ljsoncpp -ljsonrpccpp-server -ljsonrpccpp-client -ljsonrpccpp-common -lmicrohttpd -lcschnorr -lpthread -llua5.3 -lcurl -ldl -lgcov
LDDEPS += bin/Shared/Debug/libck.so
ALL_LDFLAGS += $(LDFLAGS) -Wl,-rpath,'$$ORIGIN' -rdynamic
endif

ifeq ($(config),release_static)
TARGETDIR = bin/Static/Release
TARGET = $(TARGETDIR)/ckd
OBJDIR = obj/Static/Release/ckd
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O3 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O3 -g -std=c++14
LIBS += bin/Static/Release/libck.a -lcrypto -lsfml-network -lsfml-system -lleveldb -ljsoncpp -ljsonrpccpp-server -ljsonrpccpp-client -ljsonrpccpp-common -lmicrohttpd -lcschnorr -lpthread -llua5.3 -lcurl -ldl -lgcov
LDDEPS += bin/Static/Release/libck.a
ALL_LDFLAGS += $(LDFLAGS) -rdynamic
endif

ifeq ($(config),release_shared)
TARGETDIR = bin/Shared/Release
TARGET = $(TARGETDIR)/ckd
OBJDIR = obj/Shared/Release/ckd
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O3 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O3 -g -std=c++14
LIBS += bin/Shared/Release/libck.so -lcrypto -lsfml-network -lsfml-system -lleveldb -ljsoncpp -ljsonrpccpp-server -ljsonrpccpp-client -ljsonrpccpp-common -lmicrohttpd -lcschnorr -lpthread -llua5.3 -lcurl -ldl -lgcov
LDDEPS += bin/Shared/Release/libck.so
ALL_LDFLAGS += $(LDFLAGS) -Wl,-rpath,'$$ORIGIN' -rdynamic
endif

# Per File Configurations
# #############################################


# File sets
# #############################################

OBJECTS :=

OBJECTS += $(OBJDIR)/httpserver.o
OBJECTS += $(OBJDIR)/main.o
OBJECTS += $(OBJDIR)/multicoin.o
OBJECTS += $(OBJDIR)/rpcserver.o
OBJECTS += $(OBJDIR)/wallet.o

# Rules
# #############################################

all: prebuild prelink $(TARGET) | $(TARGETDIR) $(OBJDIR)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	@echo Linking ckd
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning ckd
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH) | $(OBJDIR) $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
	$(SILENT) touch "$@"
else
$(OBJECTS): | $(OBJDIR)
endif


# File Rules
# #############################################

$(OBJDIR)/httpserver.o: src/client/httpserver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/main.o: src/client/main.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/multicoin.o: src/client/multicoin.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rpcserver.o: src/client/rpcserver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/wallet.o: src/client/wallet.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include "$(PCH_PLACEHOLDER).d"
endif