# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_static
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

# Configurations
# #############################################

RESCOMP = windres
DEFINES +=
INCLUDES += -Isrc/kernel
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef

ifeq ($(config),debug_static)
TARGETDIR = bin/Static/Debug
TARGET = $(TARGETDIR)/test
OBJDIR = obj/Static/Debug/test
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O0 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O0 -g -std=c++14
LIBS += bin/Static/Debug/libck.a -lcppunit -lcrypto -lsfml-network -lsfml-system -lleveldb -ljsoncpp -ljsonrpccpp-server -ljsonrpccpp-client -ljsonrpccpp-common -lmicrohttpd -lcschnorr -lpthread -llua5.3 -lcurl -ldl -lgcov
LDDEPS += bin/Static/Debug/libck.a
ALL_LDFLAGS += $(LDFLAGS) -rdynamic
define POSTBUILDCMDS
	@echo Running postbuild commands
	bin/Static/Debug/test
endef
endif

ifeq ($(config),debug_shared)
TARGETDIR = bin/Shared/Debug
TARGET = $(TARGETDIR)/test
OBJDIR = obj/Shared/Debug/test
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O0 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O0 -g -std=c++14
LIBS += bin/Shared/Debug/libck.so -lcppunit -lcrypto -lsfml-network -lsfml-system -lleveldb -ljsoncpp -ljsonrpccpp-server -ljsonrpccpp-client -ljsonrpccpp-common -lmicrohttpd -lcschnorr -lpthread -llua5.3 -lcurl -ldl -lgcov
LDDEPS += bin/Shared/Debug/libck.so
ALL_LDFLAGS += $(LDFLAGS) -Wl,-rpath,'$$ORIGIN' -rdynamic
define POSTBUILDCMDS
	@echo Running postbuild commands
	bin/Shared/Debug/test
endef
endif

ifeq ($(config),release_static)
TARGETDIR = bin/Static/Release
TARGET = $(TARGETDIR)/test
OBJDIR = obj/Static/Release/test
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O3 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O3 -g -std=c++14
LIBS += bin/Static/Release/libck.a -lcppunit -lcrypto -lsfml-network -lsfml-system -lleveldb -ljsoncpp -ljsonrpccpp-server -ljsonrpccpp-client -ljsonrpccpp-common -lmicrohttpd -lcschnorr -lpthread -llua5.3 -lcurl -ldl -lgcov
LDDEPS += bin/Static/Release/libck.a
ALL_LDFLAGS += $(LDFLAGS) -rdynamic
define POSTBUILDCMDS
	@echo Running postbuild commands
	bin/Static/Release/test
endef
endif

ifeq ($(config),release_shared)
TARGETDIR = bin/Shared/Release
TARGET = $(TARGETDIR)/test
OBJDIR = obj/Shared/Release/test
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O3 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O3 -g -std=c++14
LIBS += bin/Shared/Release/libck.so -lcppunit -lcrypto -lsfml-network -lsfml-system -lleveldb -ljsoncpp -ljsonrpccpp-server -ljsonrpccpp-client -ljsonrpccpp-common -lmicrohttpd -lcschnorr -lpthread -llua5.3 -lcurl -ldl -lgcov
LDDEPS += bin/Shared/Release/libck.so
ALL_LDFLAGS += $(LDFLAGS) -Wl,-rpath,'$$ORIGIN' -rdynamic
define POSTBUILDCMDS
	@echo Running postbuild commands
	bin/Shared/Release/test
endef
endif

# Per File Configurations
# #############################################


# File sets
# #############################################

OBJECTS :=

OBJECTS += $(OBJDIR)/BlockchainTests.o
OBJECTS += $(OBJDIR)/BlockchainTypesTests.o
OBJECTS += $(OBJDIR)/ContractTests.o
OBJECTS += $(OBJDIR)/CryptoKernelTestRunner.o
OBJECTS += $(OBJDIR)/CryptoTests.o
OBJECTS += $(OBJDIR)/LogTests.o
OBJECTS += $(OBJDIR)/MathTests.o
OBJECTS += $(OBJDIR)/MerkletreeTests.o
OBJECTS += $(OBJDIR)/SchnorrTests.o
OBJECTS += $(OBJDIR)/StorageTests.o

# Rules
# #############################################

all: prebuild prelink $(TARGET) | $(TARGETDIR) $(OBJDIR)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	@echo Linking test
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning test
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH) | $(OBJDIR) $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
	$(SILENT) touch "$@"
else
$(OBJECTS): | $(OBJDIR)
endif


# File Rules
# #############################################

$(OBJDIR)/BlockchainTests.o: tests/BlockchainTests.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/BlockchainTypesTests.o: tests/BlockchainTypesTests.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ContractTests.o: tests/ContractTests.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CryptoKernelTestRunner.o: tests/CryptoKernelTestRunner.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CryptoTests.o: tests/CryptoTests.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LogTests.o: tests/LogTests.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MathTests.o: tests/MathTests.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MerkletreeTests.o: tests/MerkletreeTests.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SchnorrTests.o: tests/SchnorrTests.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/StorageTests.o: tests/StorageTests.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include "$(PCH_PLACEHOLDER).d"
endif